import { useState, useEffect, useCallback } from 'react';
import type { MetricSnapshot, SessionAnalytics } from '../store/networkStore';

export function useExport() {
  const exportCSV = useCallback((history: MetricSnapshot[]) => {
    const header = 'Timestamp,Download (Mbps),Upload (Mbps),Ping (ms),Jitter (ms),Packet Loss (%),Stability\n';
    const rows = history.map((h) =>
      `${new Date(h.ts).toISOString()},${h.download.toFixed(2)},${h.upload.toFixed(2)},${h.ping},${h.jitter.toFixed(2)},${h.packetLoss},${h.stability}`
    ).join('\n');

    const blob = new Blob([header + rows], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `netpulse-session-${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  const exportJSON = useCallback((history: MetricSnapshot[], analytics: SessionAnalytics, dataConsumed: number) => {
    const data = {
      exportedAt: new Date().toISOString(),
      summary: {
        ...analytics,
        dataConsumedBytes: dataConsumed,
        dataConsumedMB: (dataConsumed / 1024 / 1024).toFixed(2)
      },
      telemetry: history
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `netpulse-session-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  const exportTXT = useCallback((history: MetricSnapshot[], analytics: SessionAnalytics, dataConsumed: number, colo: string) => {
    const mb = (dataConsumed / 1024 / 1024).toFixed(2);
    const date = new Date().toLocaleString();
    
    let txt = `=================================================\n`;
    txt += `           NETPULSE DIAGNOSTIC REPORT\n`;
    txt += `=================================================\n\n`;
    
    txt += `[ SESSION INFO ]\n`;
    txt += `Date:          ${date}\n`;
    txt += `Edge Node:     ${colo || 'Unknown'}\n`;
    txt += `Total Data:    ${mb} MB\n`;
    txt += `Samples:       ${analytics.sampleCount}\n\n`;
    
    txt += `[ PERFORMANCE SUMMARY ]\n`;
    txt += `Download:      Avg ${analytics.avgDownload.toFixed(1)} Mbps  |  Peak ${analytics.bestDownload.toFixed(1)} Mbps\n`;
    txt += `Upload:        Avg ${analytics.avgUpload.toFixed(1)} Mbps  |  Peak ${analytics.bestUpload.toFixed(1)} Mbps\n`;
    txt += `Latency:       Best ${analytics.lowestPing === Infinity ? 0 : analytics.lowestPing} ms\n`;
    txt += `Jitter:        Peak ${analytics.peakJitter.toFixed(1)} ms\n`;
    txt += `Stability:     ${analytics.avgStability.toFixed(0)} / 100\n\n`;
    
    txt += `[ DETAILED TELEMETRY LOG ]\n`;
    txt += `Time                 | Down (Mbps) | Up (Mbps) | Ping (ms) | Jitter (ms) | Loss (%) | Stability\n`;
    txt += `-------------------------------------------------------------------------------------------------\n`;
    
    history.forEach(h => {
      const t = new Date(h.ts).toLocaleTimeString().padEnd(20, ' ');
      const d = h.download.toFixed(1).padStart(11, ' ');
      const u = h.upload.toFixed(1).padStart(9, ' ');
      const p = h.ping.toString().padStart(9, ' ');
      const j = h.jitter.toFixed(1).padStart(11, ' ');
      const l = h.packetLoss.toString().padStart(8, ' ');
      const s = h.stability.toString().padStart(9, ' ');
      
      txt += `${t} | ${d} | ${u} | ${p} | ${j} | ${l} | ${s}\n`;
    });

    txt += `\n=================================================\n`;
    txt += `Generated by NetPulse - Continuous Network Diagnostics\n`;

    const blob = new Blob([txt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `netpulse-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  return { exportCSV, exportJSON, exportTXT };
}

export function useFullscreen() {
  const [isFullscreen, setIsFullscreen] = useState(false);

  useEffect(() => {
    const handler = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener('fullscreenchange', handler);
    return () => document.removeEventListener('fullscreenchange', handler);
  }, []);

  const enter = useCallback(async (el?: HTMLElement | null) => {
    const target = el ?? document.documentElement;
    try {
      await target.requestFullscreen();
    } catch { /* ignore */ }
  }, []);

  const exit = useCallback(async () => {
    try {
      await document.exitFullscreen();
    } catch { /* ignore */ }
  }, []);

  const toggle = useCallback((el?: HTMLElement | null) => {
    if (isFullscreen) exit();
    else enter(el);
  }, [isFullscreen, enter, exit]);

  return { isFullscreen, enter, exit, toggle };
}

export function useElapsedTime(startTime: number | null, active: boolean) {
  const [now, setNow] = useState<number | null>(null);

  useEffect(() => {
    if (!active || !startTime) {
      return;
    }

    const interval = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(interval);
  }, [active, startTime]);

  if (!active || !startTime) return 0;
  return Math.max(0, (now ?? startTime) - startTime);
}
